name: Ejecutar Cypress TuAlmacen cada 8 hrs

on:
  schedule:
    - cron: "0 */8 * * *"
    # - cron: "0 */30 * * *"  # Se ejecuta cada 30 minutos
    # - cron: "0 * * * *"  # Se ejecuta cada hora
  workflow_dispatch:

jobs:
  cypress-tualmacen:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Cachear el binario de Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Instalar Cypress
        run: npx cypress install

      - name: Ejecutar pruebas de TuAlmacen
        run: npx cypress run --spec "cypress/e2e/TuAlmacen/**/*" --reporter mochawesome --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true

      - name: Generar reportes XLSX desde Mochawesome
        run: node convert.js

      - name: Guardar reportes de TuAlmacen
        uses: actions/upload-artifact@v4
        with:
          name: reporte-tualmacen
          path: mochawesome-report/*.xlsx  # Se asegura que suba todos los archivos XLSX

      - name: Guardar videos de TuAlmacen
        uses: actions/upload-artifact@v4
        with:
          name: videos-tualmacen
          path: cypress/videos

      - name: Enviar notificación de TuAlmacen
        if: always()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: "Cypress Tests <${{ secrets.SMTP_USER }}>"
          to: "angel.arellan@latechfactory.com"
          subject: "Resultados de Cypress - TuAlmacen"
          body: |
            Las pruebas de TuAlmacen han finalizado. 
            Los videos están disponibles en el siguiente enlace: https://github.com/angel-arellan/comfortt/actions/workflows/cypress-tualmacen.yml

            Se adjuntan los reportes de las pruebas:
          attachments: mochawesome-report/*.xlsx  # Asegura que todos los reportes XLSX sean enviados
