name: Ejecutar Cypress cada 4 hrs 

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Cachear el binario de Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Instalar Cypress
        run: npx cypress install

      - name: Ejecutar pruebas de Cypress
        run: npx cypress run

      - name: Guardar reportes de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cypress
          path: mochawesome-report

      - name: Guardar videos de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: videos-cypress
          path: cypress/videos

      - name: Enviar notificación por correo
        if: always()  # Este paso se ejecutará siempre, independientemente del resultado de las pruebas
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: "Cypress Tests <${{ secrets.SMTP_USER }}>"
          to: "angel.arellan@latechfactory.com"
          subject: "Resultados de Cypress"
          body: |
            Las pruebas de Cypress han finalizado. Se adjunta el reporte de las pruebas.

            Puedes descargar los videos de las pruebas en los siguientes enlaces:
            - [Descargar Reporte](https://github.com/tu-repo/actions/runs/${{ github.run_id }}/artifacts/reporte-cypress)
            - [Descargar Videos](https://github.com/tu-repo/actions/runs/${{ github.run_id }}/artifacts/videos-cypress)
          attachments: |
            mochawesome-report/*.html
            cypress/videos/*.mp4


