name: Ejecutar Cypress cada 30 minutos

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      # Cache de Cypress para evitar descargar el binario cada vez
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Ejecutar pruebas Cypress
        run: npx cypress run --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Asegúrate de tener este secreto configurado en GitHub

      - name: Enviar notificación por correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: "Cypress Tests <${{ secrets.SMTP_USER }}>"
          to: "angel.arellan@latechfactory.com"
          subject: "Resultados de Cypress"
          body: "Las pruebas de Cypress han finalizado. Revisa los resultados en GitHub Actions."


