name: Ejecutar Cypress cada 60 minutos

on:
  schedule:
    - cron: "*/59 * * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      # Paso para almacenar en caché el binario de Cypress
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Instalar Cypress si no está instalado
      - name: Instalar Cypress
        run: npx cypress install

      # Ejecutar las pruebas de Cypress
      - name: Ejecutar pruebas Cypress
        run: npx cypress run --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Enviar notificación por correo
      - name: Enviar notificación por correo
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          from: "Cypress Tests <${{ secrets.SMTP_USER }}>"
          to: "angel.arellan@latechfactory.com"
          subject: "Resultados de Cypress"
          body: "Las pruebas de Cypress han finalizado y se han realizado con éxito. Para Revisar los detalles de los resultados ir a GitHub Actions."

          